//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_doctor_appointment_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int id { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> Doctorid { get; set; }
        public Nullable<System.DateTime> Date_of_Appointment { get; set; }
        public Nullable<System.DateTime> Booked_appointment_date { get; set; }
        public Nullable<int> Timeslot { get; set; }
    
        public virtual ListofDoctor ListofDoctor { get; set; }
        public virtual Timeslot Timeslot1 { get; set; }
    }
}
