//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_doctor_appointment_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListofDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListofDoctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Timeslots = new HashSet<Timeslot>();
        }
    
        public int id { get; set; }
        public Nullable<int> locid { get; set; }
        public string Doctorname { get; set; }
        public Nullable<int> Specialityid { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Hospital_location Hospital_location { get; set; }
        public virtual Specialty Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timeslot> Timeslots { get; set; }
    }
}
